version: '3'

services:

  server_mongo_database:
    image: mongo:latest
    container_name: server_mongo_database
    env_file:
      - /.env_development
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - "27017:27017"

  server_redis_database:
    image: redis:latest
    container_name: server_redis_database
    env_file:
      - /.env_development
    volumes:
      - ./redis_data:/data
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"